Use Repolib utilities to add/remove testing repos
pop-os/pop pull request #1299
Opened 2020-10-14 22:03 UTC by isantop

Since we now use Repolib for most repository management, it makes sense to do so for testing purposes and move dev repos out of sources.list. This PR attempts to use repolib/apt-manage for adding and removing repositories for testing, with a graceful fallback on add-apt-repository if repolib is not install (for continued functionality on Focal and earlier).

2020-10-21 17:33 UTC, leviport requested changes
Does not work in Focal:
```
system76@pop-os:~/pop$ ./scripts/apt remove groovy
Removing repository for 'groovy'
[sudo] password for system76: 
sudo: apt-manage: command not found
Removing preference for 'groovy'
```

2020-10-22 15:05 UTC, isantop commented
Did it actually not work, or was this just an error message? The method the script uses to fall back (`||`) still prints the error, but it should successfully fall back to `add-apt-repository`.

What's the output of `./scripts/apt local` before and after running?

2020-10-22 15:22 UTC, isantop commented
@leviport I pushed a commit which will hide the error output if the shell can't find the command. I shouldn't affect the functionality though.

2020-12-09 21:39 UTC, leviport requested changes
It looks like that `command not found` error isn't happening anymore, but I'm now getting an error with the `remove` argument:

```
system76@pop-os:~$ ./pop/scripts/apt add 3.38.2
Adding key
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Adding preference for '3.38.2'
Adding repository for '3.38.2'
system76@pop-os:~$ ./pop/scripts/apt local
3.38.2
system76@pop-os:~$ ./pop/scripts/apt remove 3.38.2
Removing repository for '3.38.2'
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 330, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 35, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Pop/groovy
system76@pop-os:~$ ./pop/scripts/apt local
3.38.2
```

2020-12-09 23:23 UTC, isantop commented
Thanks, I see what was going wrong. There needs to be some processing of the input in order to ensure that the name specified for removal is correctly passed to repolib.

2020-12-10 16:09 UTC, leviport commented
It works now, but now I'm prompted with a `(y/N)` if I try to remove a source when it used to remove the source without a prompt. I could get used to it, but it does something strange and ends up removing the source if I give it an `n` or hit enter to default to "no". It says "cancelled", then it looks like it tries again successfully:

```
system76@pop-os:~/pop$ ./scripts/apt add 3.38.2
Adding key
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Adding preference for '3.38.2'
Adding repository for '3.38.2'
system76@pop-os:~/pop$ ./scripts/apt local
3.38.2
system76@pop-os:~/pop$ ./scripts/apt remove 3.38.2
Removing repository for '3.38.2'

You are about to remove the sources contained in popdev-3-38-2.list.
Are you sure you want to do this?

Remove popdev-3-38-2.list? (y/N) 
Canceled.
Repository: 'deb http://apt.pop-os.org/staging/3.38.2 groovy main'
Description:
Archive for codename: groovy components: main
More info: http://apt.pop-os.org/staging/3.38.2
Removing repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Disabling deb entry in /etc/apt/sources.list.d/archive_uri-http_apt_pop-os_org_staging_3_38_2-groovy.list
Disabling deb-src entry in /etc/apt/sources.list.d/archive_uri-http_apt_pop-os_org_staging_3_38_2-groovy.list
Hit:1 http://apt.pop-os.org/proprietary groovy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu groovy InRelease               
Hit:3 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease      
Hit:4 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease       
Hit:5 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease
Reading package lists... Done
Removing preference for '3.38.2'
system76@pop-os:~/pop$ ./scripts/apt local
system76@pop-os:~/pop$
```

While it's technically working, it makes me feel like there is a bug.

2020-12-10 18:13 UTC, isantop commented
Ah, I see what's going on there. Cancelling the removal causes the command to exit with 1, and because that's an error it falls back to the add-apt-repository method.

Fixing that will require some changes to repolib itself which can't be worked around in the script.

2020-12-10 18:28 UTC, isantop commented
PR with requisite changes to Repolib is open: pop-os/repolib#35

2020-12-11 15:30 UTC, leviport approved these changes
20.10 is working great now. 

20.04 works fine, but adding a source does give me an error even though the source is added as expected:
`sudo: apt-manage: command not found`

Since it works despite the error, I'm approving.

2020-12-11 21:03 UTC, ids1024 commented
Although it's not hugely important if it works as expected, it's probably best not to be printing `command not found`.

It looks like `command` is the standard POSIX way to check for a command:

```bash
if command -v apt-manage > /dev/null
then
    ...
fi
```

Perhaps using a test like that would be an improvement?

2020-12-15 22:34 UTC, isantop commented
@ids1024 I've gone ahead and done that. I agree that that solution is much better, and it appears to work great on my end (although I want to make sure it passes QA on both groovy and focal).

2020-12-16 16:28 UTC, leviport approved these changes
Looking good on 20.04 and 20.10

2020-12-16 16:34 UTC, ids1024 approved these changes

2020-12-16 17:21 UTC, merged